import React from 'react';
import Head from 'next/head';
import {
	Drawer,
	DrawerBody,
	DrawerFooter,
	DrawerHeader,
	DrawerOverlay,
	DrawerContent,
	DrawerCloseButton,
	Button,
	useDisclosure,
	Input,
	Avatar,
	Center,
	Text,
	IconButton,
} from '@chakra-ui/react';
import { HamburgerIcon } from '@chakra-ui/icons';
function layout({ children }) {
	const { isOpen, onOpen, onClose } = useDisclosure();
	const btnRef = React.useRef();

	return (
		<div style={{ backgroundColor: '#624b6f' }}>
			<div style={{ padding: '1rem' }}>
				<Head>
					<title>Joaquin Niembro Bueno´s Blog</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<IconButton
					variant='ghost'
					aria-label='Call Segun'
					size='lg'
					icon={<HamburgerIcon w={10} h={10} color='white' />}
					onClick={onOpen}
					ref={btnRef}
				/>

				<Drawer
					isOpen={isOpen}
					placement='right'
					onClose={onClose}
					finalFocusRef={btnRef}
					size='xl'
					colorScheme='cyan'
				>
					<DrawerOverlay />
					<DrawerContent>
						<DrawerCloseButton />
						<Center bg='purple.600' w='100%' color='white'>
							<DrawerHeader
								style={{
									display: 'flex',
									justifyContent: 'space-around',
									alignItems: 'center',
									width: '100%',
								}}
							>
								<Text fontSize='4xl' width='container.sm'>
									Menu {'|>'} Options {'|>'} Choose {'|>'} Something to learn{' '}
								</Text>
								<Avatar
									size='2xl'
									name='Joaquin Niembro Bueno'
									src='https://media-exp1.licdn.com/dms/image/C5603AQFhdllLgUrvvg/profile-displayphoto-shrink_200_200/0/1610929643910?e=1626307200&v=beta&t=Qg_jeR-3kX8ovLq2_lUs4BIgRiEV9I_GQWest9Wanwg'
								/>
							</DrawerHeader>
						</Center>
						<DrawerFooter bg='#624b6f' height='container.xl'>
							<Button variant='outline' mr={3} onClick={onClose}>
								Cancel
							</Button>
							<Button colorScheme='blue'>Save</Button>
						</DrawerFooter>
					</DrawerContent>
				</Drawer>
				{children}
			</div>
		</div>
	);
}

export default layout;
